---
  header_logo_url:
  header_logo_text: My project
  header_links:
    - label: Home
      link: /

    - label: Bibliography
      link: /resources/tw/filter/bibliography

    - label: About
      link: /about
